server:
  port: 9293

spring:
  application:
    name: FRUIT-CONSUMER-SERVICE

# Service discovery config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
