server:
  port: 8089
spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 500
              redis-rate-limiter.burstCapacity: 1000
              redis-rate-limiter.requestedTokens: 1
#        filters:
#          - name: CircuitBreaker
#            args:
#              name: CUSTOMER-SERVICE
#              fallbackuri: forward:/customerServiceFallBack
#              name: ACCOUNT-SERVICE
#              fallbackuri: forward:/accountServiceFallBack

#    gateway:
#      routes:
#        - id: v1
#          uri: http://localhost:8081
#          predicates:
#            - Path= /customers/**
#        - id: v2
#          uri: http://localhost:8082
#          predicates:
#            - Path= /products/**
app:
  jwtSecret:
    token: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
