apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-app
spec:
  selector:
    matchLabels:
      app: customer-service-app
  template:
    metadata:
      labels:
        app: customer-service-app
    spec:
      containers:
        - name: customer-service-app
          image: ousmane1999/fruit-customers-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9292

          env:
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: hostname

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service-svc
spec:
  selector:
    app: customer-service-app
  ports:
    - port: 80
      targetPort: 9292