# custom server port
server:
  port: 9294

# MYSQL DB configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruits
    username: root
    password: ousmane2022&&!
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
    databasePlatform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: AUTHENTICATION-SERVICE

# Eureka configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expireMs: 120000
  refrEshexpireMs: 120000