# custom server port
server:
  port: 9292

# MYSQL DB configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruits
    username: root
    password: 831800
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
