# custom server port
server:
  port: 9292

# MYSQL DB configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruits
    username: root
    password: ousmane2022&&!
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: create-drop
    databasePlatform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: FRUITS-CUSTOMER-SERVICE

# Eureka configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}