server:
  port: 9291

spring:
  application:
     name: FRUITS-ORDER-SERVICE

# Eureka configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}